### ISSUE TITLE
Support TypeScript files when detecting controller folders

### ISSUE THREAD

**Issue by Intrepidd** [marcoroth/stimulus-lsp#17]
![CleanShot 2023-10-11 at 14 40 31](https://github.com/marcoroth/stimulus-lsp/assets/803765/828d3212-a99a-4d64-a25a-f395ac2ad5db)

Looks like the LSP is not finding my files, in this app they are in `app/packs/controllers` which is probably non-standard.

**Comment by Intrepidd** [comment]
My controllers are `.ts`, that's probably why all of this is happening :)

**Comment by marcoroth** [comment]
Ah I see, that explains things then, let me update this then 👍🏼

**Comment by marcoroth** [comment]
This should be resolved with v1.0.0, please re-open this issue if you still see something unexpected! Thank you!

**Comment by ViggoV** [comment]
This is still an issue with v1.0.4

**Comment by marcoroth** [comment]
Hey @ViggoV, would you mind sharing some details about your setup so I can help debug this issue?

- Which JavaScript bundler are you using?
- Where is your Stinulus controllers folder? And Controllers index file?
- In which file do you start your Stimulus Application?
- How and where do you register your Stimulus Controllers?

Thank you!

**Comment by ViggoV** [comment]
Thank for the quick response:
1 . esbuild
2. `app/javascript/`
  - `controllers/`
    - `application.js`  (starts the application)
    - `index.js` (imports application and registers controllers)
    - ...(controllers, mixed js and ts)
  -  `application.js` (imports `./controllers) 

Esbuld builds `app/javascript/*.*` (which would in this case be the application.js in that folder

Looking at it again it seems a little unconventional but I am somewhat new in the Rails world so i have used  a setup that works in other porjects (and also does its job here)

**Comment by ViggoV** [comment]
I just noticed that, in the Stimulus Controllers Explorer in the sidebar, they are recognized but sorted under "unregistered controllers"
