### ISSUE TITLE
LSP VS Code and Laravel

### ISSUE THREAD

**Issue by wizzymore** [marcoroth/stimulus-lsp#216]
Hello, i want to use this extension with Laravel and VS Code.

Can you let me know what can i do to guide the extension to the location of the controllers in my application? Currently it doesn't see any of my controllers.

I saw this PR: https://github.com/marcoroth/stimulus-lsp/pull/31 i also look in the entire code base but it's hard to understand as i don't have more knowledge of the project.

Thanks.

**Comment by marcoroth** [comment]
Hey @wizzymore, thanks for opening this issue. Technically the LSP should be able to detect it automatically.

The current 0.3.0 version requires the files to be called `*_controller.js` though. The upcoming release, which should drop within the next few days supports any `*.js` or `*.ts` in your project.

I hope this helps, if not, please let me know. In that case, it would be helpful to know where your controllers are located and how they are callled.

**Comment by wizzymore** [comment]
Thanks for the quick input, i am using typescript controllers and indeed i got it working with javascript.

Glad to know that typescript support will come soon, thanks for the project!

**Comment by marcoroth** [comment]
Awesome, thank you for the feedback. This should just work with the next release then 🙌🏼

**Comment by marcoroth** [comment]
Hey @wizzymore, this should now work with the Stimulus LSP v1.0 series. Please re-open the issue if it doesn't, thank you!
