### ISSUE TITLE
Allow custom entry point for the controllers to be scanned

### ISSUE THREAD

**Issue by agkamitsios** [marcoroth/stimulus-lsp#223]
In the project that I am working on, which is old, there is a case where the `app/javascript/controllers` is occupied by files that end with _controller but are not stimulus controllers, and we have put all the stimulus controllers inside a `app/javascript/stim/**/*` so one problem that i am facing is that i am getting false positives by files that are not stim controllers, perhaps one nice idea is to add a setting to provide an entry point to scan for controllers?

**Comment by marcoroth** [comment]
Hey @agkamitsios, thanks for opening this issue! The next version is able to handle this kind of setup by more deeply inspecting the actual files. So it shouldn't matter anymore how your files are named or where they are located, it should be able to figure it out with Zero config.

**Comment by agkamitsios** [comment]
Thank you for your time to reply! Appreciate it

**Comment by SyedMSawaid** [comment]
While we are at it, can I specify folders to scan for components?

Like right now, I am using https://github.com/palkan/view_component-contrib/ and I have component-specific controllers in `app/frontend/components`. Also, the controllers are named `controller.js`. I also do a bit of transformation on their name before registering them so... 😅

Can't we just get a list of registered controllers and call it a day? (I don't know the internals of LSP, I am just guessing)

**Comment by marcoroth** [comment]
The next version supports this 👍🏼

**Comment by marcoroth** [comment]
This should be resolved with v1.0.0, please re-open this issue if you still see something unexpected! Thank you!
