### ISSUE TITLE
Support for custom JS namespaces

### ISSUE THREAD

**Issue by davidalejandroaguilar** [marcoroth/stimulus-lsp#26]
# Description

My app has multiple namespaces: `admin` and `front_end`. These are divided in 2 entrypoints that import their own controllers, as well as a set of shared controllers:

**Entrypoints**

* `app/javascript/admin.js`

```js
import "./shared";
import "./admin/controllers";
```

* `app/javascript/front_end.js`

```js
import "./shared";
import "./front_end/controllers";
```

**Admin controllers**

* `app/javascript/admin/controllers/index.js`

```js
import { application } from "../../shared/controllers/application";

import PrintersController from "./printers_controller";
application.register("printers", PrintersController);
```

**Front end controllers**

* `app/javascript/front_end/controllers/index.js`

```js 
import { application } from "../../shared/controllers/application";

import PaymentController from "./payment_controller";
application.register("payment", PaymentController);
```

**Shared index**

* `app/javascript/shared/index.js`

```js
import "@hotwired/turbo-rails";
import "./controllers";

import { application } from "./controllers/application";

// https://www.stimulus-components.com/docs/stimulus-reveal-controller/
import Reveal from "stimulus-reveal-controller";
application.register("reveal", Reveal);
```

**Shared application**

* `app/javascript/shared/controllers/application.js`

```js 
import { Application } from "@hotwired/stimulus"

const application = Application.start()

// Configure Stimulus development experience
application.debug = false
window.Stimulus   = application

export { application }
```

**Shared controllers**

* `app/javascript/shared/controllers/index.js`

```js
import { application } from "./application";

import ModalController from "./modal_controller";
application.register("modal", ModalController);
```

**Admin layout**

```erb
<%= javascript_include_tag "admin", "data-turbo-track": "reload", defer: true %>
```

**Front end layout**

```erb
<%= javascript_include_tag "front_end", "data-turbo-track": "reload", defer: true %>
```

When on a `.html.erb` file, Stimulus LSP is referencing the wrong path, e.g. 

**On views/admin/orders/index.html.erb**

```erb
<div 
  data-controller="modal"
  data-action="click->modal#show"
></div>
```

Stimulus LSP would complain about the `data-action` attribute because `"modal isn't a valid Stimulus controller. Did you mean app--javascript--shared-controllers--modal?"`

# Versions

* Stimulus LSP v.0.1.1
* stimulus-rails 1.3.0

# Notes

Let me know if you'd like a new Rails app reproducing this or if the information above is enough to drive the discussion forward.

**Comment by davidalejandroaguilar** [comment]
Wait what? Already? Damn that was awesome! @marcoroth ⚡ , I will test the LSP again.

Thanks again!

**Comment by marcoroth** [comment]
I haven't released the fix yet, but will do it either later today or tomorrow 🙌🏼
