### ISSUE TITLE
Suggestion to register import has .ts extension

### ISSUE THREAD

**Issue by SleeplessByte** [marcoroth/stimulus-lsp#281]
When following the suggestion to import a controller:

![Quick fix for a stimulus controller](https://github.com/marcoroth/stimulus-lsp/assets/1964376/dd55fb2a-a7d6-4f7c-b4c4-409204187bb6)

The import is always added with the `.ts` extension (the file is `.ts`). However, this only works if the current `tsconfig.json` setting `allowImportingTsExtensions`. If this is set to false (default), the import fails.

> An import path can only end with a '.ts' extension when 'allowImportingTsExtensions' is enabled. ts(5097)

**Comment by marcoroth** [comment]
Thanks for reporting @SleeplessByte! That's an interesting one. I guess ideally we could just never include the file extension. That should work for both JavaScript and TypeScript in most cases.

**Comment by SleeplessByte** [comment]
I dont know if there are cases where the extension is _required_. There probably are but i would wait for the bug report to support it 😄

**Comment by marcoroth** [comment]
I don't think I added the extension on purpose, it was more a side effect while dealing with files/paths.
