### ISSUE TITLE
Cannot find bin stimulus-language-server after npm install

### ISSUE THREAD

**Issue by ttilberg** [marcoroth/stimulus-lsp#287]
Following instructions from https://github.com/marcoroth/stimulus-lsp/tree/main/server#stimulus-language-server, I am unable to find the bin referenced in running `stimulus-language-server`.

I can see that a bin entry exists in [package.json](https://github.com/marcoroth/stimulus-lsp/blob/f6174ee6d23f7bece15870cee12b99518fad94e7/server/package.json#L14), but the output directory does not include a bin stub:

```sh
~
▶ npm install -g stimulus-language-server

added 89 packages in 6s

21 packages are looking for funding
  run `npm fund` for details
Reshimming asdf nodejs...

~
▶ stimulus-language-server --stdio
zsh: command not found: stimulus-language-server

~
▶ cd $(npm ls -g | head -n 1)

nodejs/18.18.0/lib  v0.13.1 ✗
▶ cd node_modules/stimulus-language-server

lib/node_modules/stimulus-language-server  v0.13.1 ✗
▶ ls
README.md     node_modules/ out/          package.json

lib/node_modules/stimulus-language-server  v0.13.1 ✗
▶ cd out

node_modules/stimulus-language-server/out  v0.13.1 ✗
▶ ls
action_descriptor.js      code_lens.js.map          definitions.js.map        events.js                 levenshtein.js.map        server.js.map             utils.js
action_descriptor.js.map  commands.js               diagnostics.js            events.js.map             requests/                 service.js                utils.js.map
code_actions.js           commands.js.map           diagnostics.js.map        html_util.js              requests.js               service.js.map
code_actions.js.map       data_providers/           document_service.js       html_util.js.map          requests.js.map           settings.js
code_lens.js              definitions.js            document_service.js.map   levenshtein.js            server.js                 settings.js.map
```

I see there's a file in the repo `scripts/executable.mjs` that appears to have the task of generating the binstub, but it seems to not be doing its job. I'm not fluent enough in the js ecosystem to debug further.

Macos 14.2.1 
Node 18.18.0 with npm 9.8.1
Node 22.2.0 with npm 10.7.0
asdf nodejs plugin

Additionally I tried this from two different laptops.

**Comment by marcoroth** [comment]
Hey @ttilberg, thanks for opening this issue!

I think you are right, it seems like the `stimulus-language-server` executable which is supposed to be in `out/` is not actually shipped with the npm package. 

I'll check if my release GitHub Action is missing something!

This might also explain the behavior @kcdragon has been seeing in https://github.com/marcoroth/stimulus-lsp/issues/20#issuecomment-2106505606

**Comment by marcoroth** [comment]
I just published v1.0.2 which now includes the executable. If you get a chance @ttilberg, can you try that version? Thank you!

**Comment by ttilberg** [comment]
Success! Sublime is now cooking with the LSP.

Thanks!

**Comment by marcoroth** [comment]
Awesome, thanks for reporting back! I'm going to close this then 🙌🏼

**Comment by deirn** [comment]
Hey @marcoroth, it seems v1.1.0 also doesn't have the executable.

Detected by mason.nvim update job:
https://github.com/mason-org/mason-registry/pull/14510
