### ISSUE TITLE
Bug: values with dash not working?

### ISSUE THREAD

**Issue by swanson** [marcoroth/stimulus-lsp#29]
![image](https://github.com/marcoroth/stimulus-lsp/assets/56947/86b8504a-4b3a-44fd-81de-d564e3e40b82)

```js
export default class extends Controller {
  static targets = ['container']
  static values = {
    selector: String,
    frameId: String,
    url: String,
    enabled: Boolean,
    border: Boolean,
  }
```

Looks like `frameId` -> `frame-id` value is not getting parsed correctly?

**Comment by marcoroth** [comment]
This could very well be, let me see what's up here.

**Comment by marcoroth** [comment]
Yup, seems like this regex isn't flexible enough: https://github.com/marcoroth/stimulus-lsp/blob/928168563f3428c6f9992c638dd8b7b5e44dc1d6/server/src/diagnostics.ts#L26
