### ISSUE TITLE
stimulus-language-server package does not run

### ISSUE THREAD

**Issue by Gert-JanPeeters** [marcoroth/stimulus-lsp#48]
Hi, first of all thanks for this awesome LSP server.

I followed the instructions in: https://www.npmjs.com/package/stimulus-language-server. However, I am getting the following errors when I run ```stimulus-language-server --stdio```.

```
/usr/local/bin/stimulus-language-server: line 1: use strict: command not found
/usr/local/bin/stimulus-language-server: line 2: syntax error near unexpected token `exports,'
/usr/local/bin/stimulus-language-server: line 2: `Object.defineProperty(exports, "__esModule", { value: true });'
```

After some searching I found that in Unix-systems, one has to add a shebang, else the script gets run as a shell script. Indeed, when I add the following line on top of the file in ```/usr/local/bin/```, it works.

```
#!/usr/bin/env node
```

**Comment by marcoroth** [comment]
Hey @Gert-JanPeeters, thanks for opening this issue!

I had this commit sitting on my machine and I'm wondering if this resolves this issue: https://github.com/marcoroth/stimulus-lsp/pull/47/commits/35b6695e0c043bf62e24e86c8e0ace980bd7d87a

**Comment by Gert-JanPeeters** [comment]
Hi,

I think that might solve the issue. I see that it adds the shebang:

```ts
writeFileSync(
  outfile,
  '#!/usr/bin/env node\n' + readFileSync(infile, 'utf-8'),
  'utf-8'
)
```
